"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def fibonacci(n):
    assert n > 2
    a, b = 1, 2
    yield a
    yield b
    while True:
        a, b = b, a + b
        if b < n:
            yield b
        else:
            break


if __name__ == '__main__':
    seq = [i for i in fibonacci(4 * 10 ** 6) if i % 2 == 0]
    print sum(seq)
